package de.e_nexus.codereview.audit;
// Generated Aug 24, 2020, 12:52:23 PM by Hibernate Tools 5.4.19.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.envers.Audited;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", schema = "public")
@Audited
@EntityListeners(AuditingEntityListener.class)
public class Student implements java.io.Serializable {

	private int id;
	private String name;
	private Date version;
	private int classTeacher;
	private Date deletedAt;
	private Date createdAt;
	private Date modifiedAt;

	public Student() {
	}

	public Student(int id, String name, int classTeacher) {
		this.id = id;
		this.name = name;
		this.classTeacher = classTeacher;
	}

	public Student(int id, String name, int classTeacher, Date deletedAt, Date createdAt, Date modifiedAt) {
		this.id = id;
		this.name = name;
		this.classTeacher = classTeacher;
		this.deletedAt = deletedAt;
		this.createdAt = createdAt;
		this.modifiedAt = modifiedAt;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "version", length = 29)
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@Column(name = "name", nullable = false, length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "class_teacher", nullable = false)
	public int getClassTeacher() {
		return this.classTeacher;
	}

	public void setClassTeacher(int classTeacher) {
		this.classTeacher = classTeacher;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deleted_at", length = 29)
	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 29)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_at", length = 29)
	public Date getModifiedAt() {
		return this.modifiedAt;
	}

	public void setModifiedAt(Date modifiedAt) {
		this.modifiedAt = modifiedAt;
	}

}
